[tool.poetry]
name = "software-03"
version = "0.1.0"
description = "It"
authors = ["Slytherin fantom <uliadiakiv@gmail.com>"]
license = "MTI"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
